### ISSUE TITLE
No module named 'cairo'

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-py#157]
~~~
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_cairo.py", line 36, in <module>
    import cairo
ImportError: No module named 'cairo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/perprof", line 9, in <module>
    load_entry_point('perprof==1.1.0', 'console_scripts', 'perprof')()
  File "/usr/local/lib/python3.4/dist-packages/perprof-1.1.0-py3.4.egg/perprof/main.py", line 240, in main
    from . import matplotlib
  File "/usr/local/lib/python3.4/dist-packages/perprof-1.1.0-py3.4.egg/perprof/matplotlib.py", line 7, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/pyplot.py", line 109, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3agg.py", line 12, in <module>
    from .backend_cairo import cairo, HAS_CAIRO_CFFI
  File "/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_cairo.py", line 38, in <module>
    raise ImportError("Cairo backend requires that cairocffi or pycairo is installed.")
ImportError: Cairo backend requires that cairocffi or pycairo is installed.
~~~

This is probably a upstream bug or not a bug. I'm reporting it just for future reference.

**Comment by rgaiacs** [comment]
I tried

~~~
$ sudo pip3 install pycairo
~~~

but

~~~
/usr/bin/pip3 run on Wed Aug 26 11:19:58 2015
Downloading/unpacking pycairo
  Getting page https://pypi.python.org/simple/pycairo/
  URLs to search for versions for pycairo:
  * https://pypi.python.org/simple/pycairo/
  Analyzing links from page https://pypi.python.org/simple/pycairo/
    Skipping link http://cairographics.org/pycairo (from https://pypi.python.org/simple/pycairo/); not a file
    Skipping http://cairographics.org/releases/pycairo-1.8.8.tar.gz (from https://pypi.python.org/simple/pycairo/) because it is externally hosted.
  Not searching http://cairographics.org/pycairo (from https://pypi.python.org/simple/pycairo/) for files because external urls are disallowed.
  Not searching http://cairographics.org/pycairo (from https://pypi.python.org/simple/pycairo/) for files because external urls are disallowed.
  Not searching http://cairographics.org/pycairo (from https://pypi.python.org/simple/pycairo/) for files because external urls are disallowed.
  Not searching http://cairographics.org/releases/pycairo-1.8.8.tar.gz (from https://pypi.python.org/simple/pycairo/) for files because external urls are disallowed.
  Could not find any downloads that satisfy the requirement pycairo
  Some externally hosted files were ignored (use --allow-external pycairo to allow).
Cleaning up...
No distributions at all found for pycairo
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
pip.exceptions.DistributionNotFound: No distributions at all found for pycairo
~~~

I also tried

~~~
$ sudo pip3 install cairocffi
~~~

but

~~~
/usr/local/lib/python3.4/dist-packages/matplotlib/backends/backend_gtk3.py:215: Warning: Source ID 6 was not found when attempting to remove it
  GLib.source_remove(self._idle_event_id)
~~~

although the files were created

~~~
$ find perprof/examples/plots -name '*.png' 
perprof/examples/plots/abc-whiteplot.png
perprof/examples/plots/abc-blackpage.png
perprof/examples/plots/abc-m1.png
perprof/examples/plots/abc-semilog-hs.png
perprof/examples/plots/abc-semilog.png
perprof/examples/plots/abc-blackpage-whiteplot.png
perprof/examples/plots/abc.png
perprof/examples/plots/abc-t100.png
perprof/examples/plots/abc-100.png
perprof/examples/plots/abc-optimalvalues.png
perprof/examples/plots/abc-semilog-bw.png
~~~

Maybe we should include `cairocffi` at `REQUIREMENTS`.

**Comment by danijar** [comment]
Did you solve this issue? I encountered the same with another library that uses matplotlib. Usually it's best to let matplotlib figure out what backend to use so if there is no Cairo, it should automatically use Agg instead. I have no idea why this process fails though.

**Comment by rgaiacs** [comment]
> Did you solve this issue?

I didn't. =(

**Comment by danijar** [comment]
I did solve it, not sure if we have the same problem though. Uninstalled matplotlib globally using pip and installed it globally using my system's package manager. So it might just have been a broken installation.
