### ISSUE TITLE
"No such file or directory" when using fromfile_prefix_chars

### ISSUE THREAD

**Issue by rgaiacs** [ufpr-opt/perprof-py#166]
~~~
$ perprof --demo --tikz -f -o /tmp/p.pdf --lang pt_BR --title foo
~~~

works but when using [fromfile_prefix_chars](https://docs.python.org/2/library/argparse.html#fromfile-prefix-chars) as

~~~
$ cat fromfile 
--demo
--tikz
-f
-o /tmp/p.pdf
--lang pt_BR
--title foo
$ perprof @fromfile                                              
/home/raniere/src/perprof-py/perprof/main.py:218: UserWarning: Using demo mode. Ignoring input files.
  UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/perprof", line 9, in <module>
    load_entry_point('perprof==1.1.1', 'console_scripts', 'perprof')()
  File "/home/raniere/src/perprof-py/perprof/main.py", line 257, in main
    data.plot()
  File "/home/raniere/src/perprof-py/perprof/tikz.py", line 143, in plot
    with open(self.output, 'w') as file_:
FileNotFoundError: [Errno 2] No such file or directory: '/home/raniere/src/perprof-py/ /tmp/p.pdf.tex'
~~~

**Comment by rgaiacs** [comment]
User need to use

~~~
$ cat fromfile                 
--demo
--tikz
-f
-o
/tmp/p.pdf
--lang
pt_BR
--title
foo
~~~

@abelsiqueira Could you update the example at https://perprof-py.readthedocs.org/en/latest/flags.html#store-flags-in-a-file?

**Comment by lrsantos11** [comment]
Issue is closed guys?
